---
# Source: apps-template/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-stable
  annotations:
    prometheus.io/fastscrape: 'true'
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: 'http-bin-app'
---
# Source: apps-template/templates/rollout.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "http-bin-app"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "http-bin-app"
  template:
    metadata:
      labels:
        app: "http-bin-app"
    spec:
      containers:
        - image: "kennethreitz/httpbin:latest"
          name: "http-bin-app"
          ports:
            - containerPort: 80
          env:
            - name: SEMVER
              value: "latest"
            - name: STAGE
              value: dev
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            
          resources:
            limits:
              memory: 128Mi
              cpu: 1m
            requests:
              memory: 128Mi
              cpu: 1m
  minReadySeconds: 30
  revisionHistoryLimit: 3
---
# Source: apps-template/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stable-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "dev.http-bin.akpdemoapps.link"
    secretName: tls-secret
  rules:
  - host: "dev.http-bin.akpdemoapps.link"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: svc-stable
            port:
              number: 80
---
# Source: apps-template/templates/secrets-role-binding.yaml
# secret created by ESO, pushed into app specific namespace for use by kargo cred job
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-admin-creds
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: kargo-admin-creds
  data:
  - secretKey: password
    remoteRef:
      key: kargo-admin-password
      property: password
---
# Source: apps-template/templates/secrets-role-binding.yaml
# secret created by ESO, pushed into app specific namespace for use by kargo cred job
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-image-creds
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gh-image-creds
  data:
  - secretKey: password
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat
