apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-app
  namespace: demo-prod
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rollouts-app
  template:
    metadata:
      labels:
        app: rollouts-app
    spec:
      containers:
      - image: ghcr.io/eddiewebb/rollouts:1.0.30
        name: rollouts-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-svc
  namespace: demo-prod
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollouts-app
