---
# Source: apps-template/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-stable
  annotations:
    prometheus.io/fastscrape: 'true'
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: 'template-app'
---
# Source: apps-template/templates/rollout.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "template-app"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "template-app"
  template:
    metadata:
      labels:
        app: "template-app"
    spec:
      containers:
        - image: "ghcr.io/akuity/sedemo-monorepo-rollouts-app:16-purple"
          name: "template-app"
          ports:
            - containerPort: 8080
          env:
            - name: SEMVER
              value: "16-purple"
            - name: STAGE
              value: dev
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            
          resources:
            limits:
              memory: 28Mi
              cpu: 1m
            requests:
              memory: 28Mi
              cpu: 1m
  minReadySeconds: 30
  revisionHistoryLimit: 3
---
# Source: apps-template/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stable-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "dev.eddie.akpdemoapps.link"
    secretName: tls-secret
  rules:
  - host: "dev.eddie.akpdemoapps.link"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: svc-stable
            port:
              number: 80

