---
# Source: apps-template/templates/secrets-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-reader-binding-team-eddie-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: 'team-eddie-dev'
---
# Source: apps-template/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-stable
  annotations:
    prometheus.io/fastscrape: 'true'
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: 'team-eddie-app'
---
# Source: apps-template/templates/rollout.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "team-eddie-app"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "team-eddie-app"
  template:
    metadata:
      labels:
        app: "team-eddie-app"
    spec:
      containers:
        - image: "ghcr.io/akuity/sedemo-monorepo-rollouts-app:14-blue"
          name: "team-eddie-app"
          ports:
            - containerPort: 8080
          env:
            - name: SEMVER
              value: "14-blue"
            - name: STAGE
              value: dev
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
  minReadySeconds: 30
  revisionHistoryLimit: 3
---
# Source: apps-template/templates/kargo-creds-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-kargo-creds
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    #argocd.argoproj.io/hook: PostSync. #app depends on branch created by kargo workflow, and won't be healthy until then, post sync wont work
    # instead we set a sync-wave on the app of apps to ensure it comes after the kargo project
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kargo-sync
        image: "ghcr.io/akuity/sedemo-monorepo-kargo-cred-sync-job:latest"
        pullPolicy: Always
        env:
        - name: GITHUB_USER
          value: "eddiewebb"
        - name: GITHUB_ORG
          value: "akuity"
        - name: KARGO_PROJECT
          value: "team-eddie"
        - name: KARGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kargo-admin-creds
              key: password
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: gh-image-creds
              key: pat
  backoffLimit: 4
---
# Source: apps-template/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stable-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "dev.eddie.akpdemoapps.link"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: svc-stable
            port:
              number: 80
