---
# Source: apps-template/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-stable
  annotations:
    prometheus.io/fastscrape: 'true'
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: 'eddies-team-app'
---
# Source: apps-template/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-canary
  annotations:
    prometheus.io/fastscrape: 'true'
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: 'eddies-team-app'
---
# Source: apps-template/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stable-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "prod.eddie.akpdemoapps.link"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: svc-stable
            port:
              number: 80
---
# Source: apps-template/templates/analysis.yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 15s
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    # If there is no traffic to demo app during rollout we will have empty set.
    successCondition: len(result) == 0 || result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-server.prometheus.svc.cluster.local
        query: |
          ( sum(rate(nginx_ingress_controller_requests{namespace="eddies-team-prod",status="200",canary="eddies-team-prod-svc-canary-80"}[30s])) + 1 )
          /
          ( sum(rate(nginx_ingress_controller_requests{namespace="eddies-team-prod",canary="eddies-team-prod-svc-canary-80"}[30s])) + 1 )
---
# Source: apps-template/templates/loadgen.yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: loadgen
spec:
  metrics:
  - name: load-gen
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: loadgen
                image: jordi/ab
                command: [ab,"-n20","http://prod.eddie.akpdemoapps.link/"]
              restartPolicy: Never
          backoffLimit: 1
---
# Source: apps-template/templates/rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: "eddies-team-app"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "eddies-team-app"
  template:
    metadata:
      labels:
        app: "eddies-team-app"
    spec:
      containers:
        - image: "ghcr.io/akuity/sedemo-monorepo-rollouts-app:8-blue"
          name: "eddies-team-app"
          ports:
            - containerPort: 8080
          env:
            - name: SEMVER
              value: "8-blue"
            - name: STAGE
              value: prod
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      canaryService: svc-canary  # required
      stableService: svc-stable # required
      trafficRouting:
        nginx:
          stableIngress: stable-ingress
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 4
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 20s 
        - setWeight: 20
        - analysis:
            templates:
            - templateName: loadgen
        - pause:
            duration: 20s 
        - setWeight: 50
        - pause:
            duration: 1m 
        - setWeight: 75
        - pause:
            duration: 20s 
        - setWeight: 100
