apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-app
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rollouts-app
  template:
    metadata:
      labels:
        app: rollouts-app
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: rollouts-app
          ports:
            - containerPort: 8080
          env:
            - name: SEMVER
              valueFrom:
                fieldRef:
                  fieldPath: "{{.Values.image.tag}}"
            - name: STAGE
              valueFrom:
                fieldRef:
                  fieldPath: {{.Values.kargo.stage}}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespaces