apiVersion: v1
kind: Service
metadata:
  name: rollouts-svc-stable
  annotations:
    prometheus.io/fastscrape: true
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollouts-app
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-svc-canary
  annotations:
    prometheus.io/fastscrape: true
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollouts-app