apiVersion: v1
kind: Service
metadata:
  name: rollouts-svc-stable
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollouts-app
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-svc-canary
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollouts-app