apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: demo-prod

labels:
  - pairs:
      rollouts-app/stage: "prod"
    includeTemplates: true   # Apply label to po