apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/eddiewebb/rollouts
  newName: ghcr.io/eddiewebb/rollouts
  newTag: v0.0.1

labels:
- includeTemplates: true
  pairs:
    rollouts-app/stage: prod

replacements:
- source:
    fieldPath: spec.template.spec.containers.[name=rollouts-app].image
    kind: Deployment
    options:
      delimiter: ':'
      index: 1
  targets:
  - fieldPaths:
    - metadata.labels.[app.kubernetes.io/version]
    - spec.template.metadata.labels.[app.kubernetes.io/version]
    options:
      create: true
    select:
      kind: Deployment
      name: rollouts-app

patches:
- path: nodeport.yaml
