version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@2.1.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/build.yml
          exclude: |
            deploy/.*
            .circleci/.*
          mapping: |
            .* build-image true