apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rollouts-app
  template:
    metadata:
      labels:
        app: rollouts-app
    spec:
      containers:
        - image: ghcr.io/eddiewebb/rollouts
          name: rollouts-app
          ports:
            - containerPort: 8080
          env:
            - name: COLOR
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['rollouts-app/color']
            - name: SEMVER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
            - name: STAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['rollouts-app/stage']
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace