apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rollouts-app
  template:
    metadata:
      labels:
        app: rollouts-app
    spec:
      containers:
        - image: ghcr.io/eddiewebb/rollouts
          name: rollouts-app
          ports:
            - containerPort: 8080