apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-dev

resources:
- deployment.yaml
- service.yaml




replacements:
  - source:
      kind: Deployment
      fieldPath: spec.template.spec.containers.[name=rollouts-app].image
      options:
        delimiter: ":"
        index: 1 
    targets:
      - select:
          name: rollouts-app
          kind: Deployment
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/version]
          - spec.template.metadata.labels.[app.kubernetes.io/version] 
        options:
          create: true