apiVersion: v1
kind: Service
metadata:
  name: rollouts-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollouts-app
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-nodeport
spec:
  type: NodePort
  selector:
    app: rollouts-app
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 50000