apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: demo-dev
images:
- name: ghcr.io/eddiewebb/rollouts
  newName: ghcr.io/eddiewebb/rollouts
  newTag: v0.0.1