apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: demo-staging
images:
- name: ghcr.io/eddiewebb/rollouts
  newName: ghcr.io/eddiewebb/rollouts
  newTag: v0.0.1

labels:
  - pairs:
      rollouts-app/stage: "staging"
    includeTemplates: true   # Apply label to po

replacements:
  - source:
      kind: Deployment
      fieldPath: spec.template.spec.containers.[name=rollouts-app].image
      options:
        delimiter: ":"
        index: 1 
    targets:
      - select:
          name: rollouts-app
          kind: Deployment
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/version]
          - spec.template.metadata.labels.[app.kubernetes.io/version] 
        options:
          create: true